# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b4ef7d3f53f2f93a94325a5f9776848f5c2e27a23468380f9cf936c75d6b6df9a3673c27f9282e39dd3c745ad2ca4dd87ee273053d7c3318f06a71d5d323d964

test:
  secret_key_base: ebcd8129519429e2816457545935382de51b82ab8542d1cc9c1c297c1942b19e90e7066efd26f489920457d01f5d1e9cf11d86692bb3d47903c28aa7e8c5150d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
